2024-12-28-00-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 3
 2024-12-28-00-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-01-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 4
 2024-12-28-01-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-02-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 5
 2024-12-28-02-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-03-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 6
 2024-12-28-03-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-04-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 7
 2024-12-28-04-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-05-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 8
 2024-12-28-05-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-06-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 9
 2024-12-28-06-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-07-44 [HikariPool-1 connection adder] [ERROR] [com.zaxxer.hikari.pool.HikariPool]  - HikariPool-1 - Error thrown while acquiring connection from data source
 com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,001 milliseconds ago. The last packet sent successfully to the server was 10,001 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1364) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1349) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:404) ~[HikariCP-5.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365) ~[HikariCP-5.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) [HikariCP-5.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) [HikariCP-5.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) [HikariCP-5.1.0.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 10,001 milliseconds ago. The last packet sent successfully to the server was 10,001 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:157) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.NativeSession.queryServerVariable(NativeSession.java:593) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1356) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	... 11 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1455) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059) ~[?:?]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:157) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.NativeSession.queryServerVariable(NativeSession.java:593) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1356) ~[mysql-connector-j-8.3.0.jar:8.3.0]
	... 11 more
2024-12-28-07-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 10
 2024-12-28-07-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 2024-12-28-08-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - Begin update Certificates. total updates: 11
 2024-12-28-08-56 [auto-certificate-service-daemon-1] [INFO] [com.wechat.pay.java.core.certificate.AutoCertificateService]  - update wechatpay certificate 1645631772-RSA done
 